### ISSUE TITLE
Clicking Asset Indexer shows empty pane on right side.

### ISSUE THREAD

**Issue by subratom** [a-digital/assetindexer#1]
I installed this plugin to see if I can get it to run on about 130K assets (3 folders) and clicking on Asset Indexer shows an empty page. Anyway to know if there is an error?
![screenshot118](https://cloud.githubusercontent.com/assets/9561837/20271112/b40d57ac-aa57-11e6-8530-3cab18de8456.png)

**Comment by matt-adigital** [comment]
Thank you for downloading our plugin. Are the folders held over on Amazon S3? We developed this for a particular issue we had ourselves with S3 before releasing it to help others with similar issues. As a result we only display the S3 asset sources within craft for indexing within this plugin.

**Comment by subratom** [comment]
Ah I see, no I am using local folders. Would it be easy to make it to look at local folders? We will be moving away from AWS to Azure, so I didnt want to rely on S3.

**Comment by matt-adigital** [comment]
Currently it does not look at local folders and we hadn't planned on adding this functionality in the near future. It could be something we could look into but if you need it sooner and are capable enough, then please feel free to submit a pull request. We are happy for the community to develop this in ways we hadn't originally thought of, but this could be something we look at in time.

**Comment by matt-adigital** [comment]
If you still need local sources to be indexed then please use [Batch Asset Indexer](https://github.com/bymayo/batch-asset-indexer) which has recently been created by [bymayo](https://github.com/bymayo) as a result of this plugin.
