### ISSUE TITLE
/admin path is hard-coded as /cms

### ISSUE THREAD

**Issue by BenParizek** [a-digital/assetindexer#3]
This plugin seems to assume our CP Trigger is `/cms`. 

Would be good to update the code to let that value be dynamic:

    $cpTrigger = craft()->config->get('cpTrigger')

**Comment by matt-adigital** [comment]
Thanks Ben, I've updated and put out a new release. Easy to miss small things like this when it originally started out life for internal usage only, thank you for your feedback.
