### ISSUE TITLE
Indexer for local files

### ISSUE THREAD

**Issue by outline4** [a-digital/assetindexer#6]
Hi, I am running into the same issues but I only have local files. 

Are you ever thinking of integrating local files?   
Or do you think it would be hard for me to rewrite the plugin to fit my needs? I am an absolute plugin noob... 

Cheers  
Stefan

**Comment by matt-adigital** [comment]
This plugin only indexes S3 asset sources. If you need local sources to be indexed then please use [Batch Asset Indexer](https://github.com/bymayo/batch-asset-indexer) which has recently been created by [bymayo](https://github.com/bymayo)
